/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationScenario {
  'id' : bigint,
  'title' : string,
  'xpReward' : bigint,
  'languageId' : bigint,
  'description' : string,
  'steps' : Array<DialogueStep>,
}
export interface CultureContent {
  'title' : string,
  'content' : string,
  'xpReward' : bigint,
  'languageText' : string,
  'translatedText' : string,
}
export interface DialogueStep {
  'expectedResponse' : string,
  'prompt' : string,
  'speaker' : string,
}
export type GameMode = { 'listeningComprehension' : null } |
  { 'sentenceBuilder' : null } |
  { 'vocabularyQuiz' : null } |
  { 'repeatableChallenge' : null } |
  { 'wordMatch' : null };
export interface Language {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface MinigameConfig {
  'id' : bigint,
  'timeLimit' : [] | [bigint],
  'xpReward' : bigint,
  'languageId' : bigint,
  'difficulty' : bigint,
  'instructions' : string,
  'gameMode' : GameMode,
}
export interface UserProfile {
  'xp' : bigint,
  'name' : string,
  'selectedLanguage' : bigint,
  'level' : bigint,
}
export interface UserProgress {
  'xp' : bigint,
  'completedCultureEntries' : Array<bigint>,
  'selectedLanguage' : bigint,
  'level' : bigint,
  'completedMinigames' : Array<[bigint, GameMode, bigint]>,
  'completedDialogues' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeCultureEntry' : ActorMethod<[bigint, bigint], undefined>,
  'completeDialogue' : ActorMethod<[bigint, bigint], undefined>,
  'completeMinigame' : ActorMethod<[GameMode, bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationScenarios' : ActorMethod<
    [bigint, bigint, bigint],
    Array<ConversationScenario>
  >,
  'getCultureEntries' : ActorMethod<
    [bigint, bigint, bigint],
    Array<CultureContent>
  >,
  'getLanguages' : ActorMethod<[bigint, bigint], Array<Language>>,
  'getMinigameConfigs' : ActorMethod<
    [bigint, bigint, bigint],
    Array<MinigameConfig>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSelectedLanguage' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];