/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'listeningComprehension' : IDL.Null,
  'sentenceBuilder' : IDL.Null,
  'vocabularyQuiz' : IDL.Null,
  'repeatableChallenge' : IDL.Null,
  'wordMatch' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'selectedLanguage' : IDL.Nat,
  'level' : IDL.Nat,
});
export const DialogueStep = IDL.Record({
  'expectedResponse' : IDL.Text,
  'prompt' : IDL.Text,
  'speaker' : IDL.Text,
});
export const ConversationScenario = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'xpReward' : IDL.Nat,
  'languageId' : IDL.Nat,
  'description' : IDL.Text,
  'steps' : IDL.Vec(DialogueStep),
});
export const CultureContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'xpReward' : IDL.Nat,
  'languageText' : IDL.Text,
  'translatedText' : IDL.Text,
});
export const Language = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MinigameConfig = IDL.Record({
  'id' : IDL.Nat,
  'timeLimit' : IDL.Opt(IDL.Nat),
  'xpReward' : IDL.Nat,
  'languageId' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'instructions' : IDL.Text,
  'gameMode' : GameMode,
});
export const UserProgress = IDL.Record({
  'xp' : IDL.Nat,
  'completedCultureEntries' : IDL.Vec(IDL.Nat),
  'selectedLanguage' : IDL.Nat,
  'level' : IDL.Nat,
  'completedMinigames' : IDL.Vec(IDL.Tuple(IDL.Nat, GameMode, IDL.Nat)),
  'completedDialogues' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeCultureEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'completeDialogue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'completeMinigame' : IDL.Func([GameMode, IDL.Nat, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationScenarios' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(ConversationScenario)],
      ['query'],
    ),
  'getCultureEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(CultureContent)],
      ['query'],
    ),
  'getLanguages' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Language)], ['query']),
  'getMinigameConfigs' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(MinigameConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSelectedLanguage' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'listeningComprehension' : IDL.Null,
    'sentenceBuilder' : IDL.Null,
    'vocabularyQuiz' : IDL.Null,
    'repeatableChallenge' : IDL.Null,
    'wordMatch' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'selectedLanguage' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const DialogueStep = IDL.Record({
    'expectedResponse' : IDL.Text,
    'prompt' : IDL.Text,
    'speaker' : IDL.Text,
  });
  const ConversationScenario = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'xpReward' : IDL.Nat,
    'languageId' : IDL.Nat,
    'description' : IDL.Text,
    'steps' : IDL.Vec(DialogueStep),
  });
  const CultureContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'xpReward' : IDL.Nat,
    'languageText' : IDL.Text,
    'translatedText' : IDL.Text,
  });
  const Language = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MinigameConfig = IDL.Record({
    'id' : IDL.Nat,
    'timeLimit' : IDL.Opt(IDL.Nat),
    'xpReward' : IDL.Nat,
    'languageId' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'instructions' : IDL.Text,
    'gameMode' : GameMode,
  });
  const UserProgress = IDL.Record({
    'xp' : IDL.Nat,
    'completedCultureEntries' : IDL.Vec(IDL.Nat),
    'selectedLanguage' : IDL.Nat,
    'level' : IDL.Nat,
    'completedMinigames' : IDL.Vec(IDL.Tuple(IDL.Nat, GameMode, IDL.Nat)),
    'completedDialogues' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeCultureEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'completeDialogue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'completeMinigame' : IDL.Func([GameMode, IDL.Nat, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationScenarios' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(ConversationScenario)],
        ['query'],
      ),
    'getCultureEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(CultureContent)],
        ['query'],
      ),
    'getLanguages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Language)],
        ['query'],
      ),
    'getMinigameConfigs' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(MinigameConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSelectedLanguage' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };